# Generated by Django 4.1.3 on 2023-05-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_coupon_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_amount',
            field=models.IntegerField(default=499),
        ),
    ]
