# Generated by Django 4.1.3 on 2023-05-13 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_coupon_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_address',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='order_address_details',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('mob_no', models.CharField(max_length=12)),
                ('line', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField()),
                ('order_add_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Home.order_address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
