# Generated by Django 4.1.3 on 2023-05-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
