# Generated by Django 4.1.3 on 2023-05-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amounts',
            field=models.IntegerField(default=0),
        ),
    ]
