# Generated by Django 4.1.3 on 2023-06-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Order Recieved', 'Order Recieved'), ('Baking', 'Baking'), ('Baked', 'Baked'), ('Out for delivery', 'Out for delivery'), ('delivered ', 'delivered ')], default='Order Recieved', max_length=50),
        ),
    ]
