# Generated by Django 4.1.3 on 2023-04-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rest_registration',
            fields=[
                ('rest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=60)),
                ('owner_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('days', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
