# Generated by Django 4.1.3 on 2023-05-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='menus')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.rest_registration')),
            ],
        ),
    ]
