# Generated by Django 4.1.3 on 2023-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest_registration',
            name='food_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rest_registration',
            name='img',
            field=models.ImageField(default='', upload_to='resturant_img'),
            preserve_default=False,
        ),
    ]
