# Generated by Django 4.1.3 on 2023-06-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_rest_registration_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest_registration',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
