# Generated by Django 4.1.3 on 2023-07-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_rest_registration_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='Restaurant.rest_registration'),
        ),
    ]
