# Generated by Django 4.1.3 on 2023-09-13 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='createAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
